"""tag and student_tag m2m

Revision ID: 7cfc4d9b5eab
Revises: 527d1b8966c2
Create Date: 2026-05-17 20:21:46.752936

"""
from alembic import op
import sqlalchemy as sa


revision = '7cfc4d9b5eab'
down_revision = '527d1b8966c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_tag',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'tag_id')
    )
    # assignment 5 gold, the composite PK already covers (student_id, tag_id)
    # but lookups by tag alone need a dedicated index, and the heavy stat
    # also benefits from one on student.grade so the aggregate stays cheap
    op.create_index('ix_student_tag_tag', 'student_tag', ['tag_id'])
    op.create_index('ix_student_grade',   'student',     ['grade'])


def downgrade() -> None:
    op.drop_index('ix_student_grade',   table_name='student')
    op.drop_index('ix_student_tag_tag', table_name='student_tag')
    op.drop_table('student_tag')
    op.drop_table('tag')
